framework:
    cache:
        # Unique name for cache keys stability
        prefix_seed: portalznackare_api
        
        # Default app cache - filesystem pro základní cache
        app: cache.adapter.filesystem

        # Specialized cache pools pro API optimalizaci
        pools:
            # API cache pool - pro INSYZ data caching
            app.api_cache:
                adapter: cache.adapter.redis
                provider: 'redis://localhost:6379/0'
                default_lifetime: 600  # 10 minut default
                
            # Long-term cache pro user data a statická data  
            app.long_cache:
                adapter: cache.adapter.redis
                provider: 'redis://localhost:6379/1'  
                default_lifetime: 1800  # 30 minut

        # Redis fallback pro production (pokud Redis není dostupný)
        default_redis_provider: 'redis://localhost:6379'
