framework:
    messenger:
        # Synchronous is default for test env
        default_bus: messenger.bus.default
        
        # Configure the buses
        buses:
            messenger.bus.default:
                default_middleware: allow_no_handlers
                middleware:
                    - validation
                    - doctrine_transaction
        
        # Transport configuration
        transports:
            # Database transport for async processing
            async:
                dsn: 'doctrine://default'
                options:
                    auto_setup: true
                    check_delayed_interval: 60000
            # Failed messages transport
            failed:
                dsn: 'doctrine://default?queue_name=failed'
        
        # Routing - which messages go to which transport
        routing:
            App\Message\SendToInsyzMessage:
                senders: ['async']
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 10000
        
        # Failure transport for failed messages
        failure_transport: failed