webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    
    # The project directory where compiled assets will be stored
    # output_path: '%kernel.project_dir%/public/build'
    # If multiple builds are defined (as shown below)
    # you can disable the default build:
    # output_path: false

    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true
        # Uncomment any of the following lines if you need it
        # defer: false
        # async: false
        # module: false
        # nonce: '%csp_nonce%'
    # link_attributes:
        # Set attributes that will be rendered on all link tags
        # referrerpolicy: origin

    # You can optionally configure other Webpack Encore features here:
    # preload: true
    crossorigin: 'anonymous'
    
    # Features that require the Stimulus or Turbo packages
    # stimulus: ~
    # turbo: ~

    # If using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'

    # Cache the entrypoints.json (rebuild only when backend changes)
    # Put in config/packages/prod/webpack_encore.yaml
    # cache: true

# Uncomment to enable the build_full_path option
# when@prod:
#     webpack_encore:
#         # Possible values are true, false or absolute path like %kernel.project_dir%/public/build/
#         build_full_path: true

# Uncomment if you're using multiple builds
# webpack_encore:
#     builds:
#         frontend: '%kernel.project_dir%/public/frontend/build'
#         admin: '%kernel.project_dir%/public/admin/build'