<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251107075124 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Update soft deleted pages to use DELETED status instead of just deleted_at timestamp';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_file_deleted');
        $this->addSql('DROP INDEX idx_file_temporary');
        $this->addSql('DROP INDEX idx_file_uploaded_by');
        $this->addSql('ALTER TABLE file_attachments ALTER storage_path TYPE VARCHAR(500)');
        $this->addSql('ALTER TABLE file_attachments ALTER storage_path DROP DEFAULT');
        $this->addSql('ALTER TABLE file_attachments ALTER is_temporary TYPE BOOLEAN');
        $this->addSql('ALTER TABLE file_attachments ALTER is_temporary DROP DEFAULT');
        $this->addSql('ALTER TABLE file_attachments ALTER physically_deleted TYPE BOOLEAN');
        $this->addSql('ALTER TABLE file_attachments ALTER physically_deleted DROP DEFAULT');
        $this->addSql('CREATE INDEX idx_file_storage_path ON file_attachments (storage_path)');
        $this->addSql('DROP INDEX idx_pages_deleted_at');
        $this->addSql('DROP INDEX idx_pages_sort_order');
        $this->addSql('DROP INDEX idx_pages_title_trgm');
        $this->addSql('DROP INDEX idx_pages_content_trgm');
        $this->addSql('DROP INDEX idx_pages_author');
        $this->addSql('DROP INDEX idx_pages_published_at');
        $this->addSql('DROP INDEX idx_pages_slug');
        $this->addSql('DROP INDEX idx_pages_status');
        $this->addSql('DROP INDEX idx_pages_content_type');
        $this->addSql('DROP INDEX idx_pages_excerpt_trgm');
        $this->addSql('ALTER TABLE pages ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE pages ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE pages ALTER content TYPE TEXT');
        $this->addSql('ALTER TABLE pages ALTER excerpt TYPE TEXT');
        $this->addSql('ALTER TABLE pages ALTER content_type TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE pages ALTER content_type DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER status TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE pages ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER sort_order TYPE INT');
        $this->addSql('ALTER TABLE pages ALTER sort_order DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER meta TYPE JSON');
        $this->addSql('ALTER TABLE pages ALTER meta DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER meta SET NOT NULL');
        $this->addSql('ALTER TABLE pages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE pages ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE pages ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER history TYPE JSON');
        $this->addSql('ALTER TABLE pages ALTER history DROP DEFAULT');
        $this->addSql('ALTER TABLE pages ALTER history SET NOT NULL');
        $this->addSql('COMMENT ON COLUMN pages.content IS \'\'');
        $this->addSql('COMMENT ON COLUMN pages.excerpt IS \'\'');
        $this->addSql('COMMENT ON COLUMN pages.content_type IS \'\'');
        $this->addSql('COMMENT ON COLUMN pages.status IS \'\'');
        $this->addSql('COMMENT ON COLUMN pages.meta IS \'\'');
        $this->addSql('COMMENT ON COLUMN pages.history IS \'\'');
        $this->addSql('ALTER INDEX pages_slug_key RENAME TO UNIQ_2074E575989D9B62');
        $this->addSql('ALTER INDEX idx_pages_parent RENAME TO IDX_2074E575727ACA70');

        // Data migration: Update all soft deleted pages to use DELETED status
        $this->addSql('UPDATE pages SET status = \'deleted\' WHERE deleted_at IS NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_file_storage_path');
        $this->addSql('ALTER TABLE file_attachments ALTER storage_path TYPE VARCHAR(500)');
        $this->addSql('ALTER TABLE file_attachments ALTER storage_path SET DEFAULT \'\'');
        $this->addSql('ALTER TABLE file_attachments ALTER is_temporary TYPE BOOLEAN');
        $this->addSql('ALTER TABLE file_attachments ALTER is_temporary SET DEFAULT false');
        $this->addSql('ALTER TABLE file_attachments ALTER physically_deleted TYPE BOOLEAN');
        $this->addSql('ALTER TABLE file_attachments ALTER physically_deleted SET DEFAULT false');
        $this->addSql('CREATE INDEX idx_file_deleted ON file_attachments (deleted_at, physically_deleted)');
        $this->addSql('CREATE INDEX idx_file_temporary ON file_attachments (is_temporary, expires_at)');
        $this->addSql('CREATE INDEX idx_file_uploaded_by ON file_attachments (uploaded_by)');
        $this->addSql('ALTER TABLE pages ALTER id TYPE BIGINT');
        $this->addSql('ALTER TABLE pages ALTER id SET DEFAULT nextval(\'pages_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE pages ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE pages ALTER content TYPE TEXT');
        $this->addSql('ALTER TABLE pages ALTER excerpt TYPE TEXT');
        $this->addSql('ALTER TABLE pages ALTER content_type TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE pages ALTER content_type SET DEFAULT \'page\'');
        $this->addSql('ALTER TABLE pages ALTER status TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE pages ALTER status SET DEFAULT \'draft\'');
        $this->addSql('ALTER TABLE pages ALTER sort_order TYPE INT');
        $this->addSql('ALTER TABLE pages ALTER sort_order SET DEFAULT 0');
        $this->addSql('ALTER TABLE pages ALTER meta TYPE JSON');
        $this->addSql('ALTER TABLE pages ALTER meta SET DEFAULT \'{}\'');
        $this->addSql('ALTER TABLE pages ALTER meta DROP NOT NULL');
        $this->addSql('ALTER TABLE pages ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE pages ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE pages ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE pages ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE pages ALTER history TYPE JSON');
        $this->addSql('ALTER TABLE pages ALTER history SET DEFAULT \'[]\'');
        $this->addSql('ALTER TABLE pages ALTER history DROP NOT NULL');
        $this->addSql('COMMENT ON COLUMN pages.content IS \'HTML content from Tiptap WYSIWYG editor\'');
        $this->addSql('COMMENT ON COLUMN pages.excerpt IS \'Optional short summary/perex\'');
        $this->addSql('COMMENT ON COLUMN pages.content_type IS \'Content classification: page, article, document, faq\'');
        $this->addSql('COMMENT ON COLUMN pages.status IS \'Workflow status: draft, published, archived\'');
        $this->addSql('COMMENT ON COLUMN pages.meta IS \'SEO metadata: seo_title, seo_description, keywords\'');
        $this->addSql('COMMENT ON COLUMN pages.history IS \'Changelog array: [{timestamp, user_id, action, changes}]\'');
        $this->addSql('CREATE INDEX idx_pages_deleted_at ON pages (deleted_at)');
        $this->addSql('CREATE INDEX idx_pages_sort_order ON pages (sort_order)');
        $this->addSql('CREATE INDEX idx_pages_title_trgm ON pages (title)');
        $this->addSql('CREATE INDEX idx_pages_content_trgm ON pages (content)');
        $this->addSql('CREATE INDEX idx_pages_author ON pages (author_id)');
        $this->addSql('CREATE INDEX idx_pages_published_at ON pages (published_at)');
        $this->addSql('CREATE INDEX idx_pages_slug ON pages (slug) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE INDEX idx_pages_status ON pages (status)');
        $this->addSql('CREATE INDEX idx_pages_content_type ON pages (content_type)');
        $this->addSql('CREATE INDEX idx_pages_excerpt_trgm ON pages (excerpt)');
        $this->addSql('ALTER INDEX uniq_2074e575989d9b62 RENAME TO pages_slug_key');
        $this->addSql('ALTER INDEX idx_2074e575727aca70 RENAME TO idx_pages_parent');
    }
}
