<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250810155354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT audit_logs_user_id_fkey');
        $this->addSql('DROP INDEX idx_audit_logs_int_adr_action');
        $this->addSql('DROP INDEX idx_audit_logs_int_adr_created');
        $this->addSql('DROP INDEX idx_audit_logs_entity_actions');
        $this->addSql('ALTER TABLE audit_logs ALTER id TYPE INT');
        $this->addSql('ALTER TABLE audit_logs ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE audit_logs ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE audit_logs ALTER ip_address TYPE VARCHAR(45)');
        $this->addSql('ALTER TABLE audit_logs ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE audit_logs ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT FK_D62F2858A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE insyz_audit_logs DROP CONSTRAINT fk_insyz_audit_user');
        $this->addSql('DROP INDEX idx_insyz_audit_created_at');
        $this->addSql('DROP INDEX idx_insyz_audit_duration');
        $this->addSql('DROP INDEX idx_insyz_audit_mssql_duration');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER id TYPE INT');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER cache_hit TYPE BOOLEAN');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER cache_hit DROP DEFAULT');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE insyz_audit_logs ADD CONSTRAINT FK_1C3D7531A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE system_options ALTER id TYPE INT');
        $this->addSql('ALTER TABLE system_options ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE system_options ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE system_options ALTER autoload TYPE BOOLEAN');
        $this->addSql('ALTER TABLE system_options ALTER autoload DROP DEFAULT');
        $this->addSql('ALTER TABLE system_options ALTER autoload SET NOT NULL');
        $this->addSql('ALTER TABLE system_options ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE system_options ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE system_options ALTER created_at SET NOT NULL');
        $this->addSql('ALTER TABLE system_options ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE system_options ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE system_options ALTER updated_at SET NOT NULL');
        $this->addSql('ALTER INDEX system_options_option_name_key RENAME TO UNIQ_3C468614B62DD4E5');
        $this->addSql('DROP INDEX idx_users_email');
        $this->addSql('DROP INDEX idx_users_is_active');
        $this->addSql('DROP INDEX idx_users_last_login');
        $this->addSql('ALTER TABLE users ALTER id TYPE INT');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE users ALTER roles TYPE JSON');
        $this->addSql('ALTER TABLE users ALTER roles DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER preferences TYPE JSON');
        $this->addSql('ALTER TABLE users ALTER preferences DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER settings TYPE JSON');
        $this->addSql('ALTER TABLE users ALTER settings DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE users ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE users ALTER updated_at DROP DEFAULT');
        $this->addSql('ALTER TABLE users ALTER is_active TYPE BOOLEAN');
        $this->addSql('ALTER TABLE users ALTER is_active DROP DEFAULT');
        $this->addSql('ALTER INDEX users_int_adr_key RENAME TO UNIQ_1483A5E9D80FFE3D');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE audit_logs DROP CONSTRAINT FK_D62F2858A76ED395');
        $this->addSql('ALTER TABLE audit_logs ALTER id TYPE INT');
        $this->addSql('ALTER TABLE audit_logs ALTER id SET DEFAULT nextval(\'audit_logs_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE audit_logs ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE audit_logs ALTER ip_address TYPE VARCHAR');
        $this->addSql('ALTER TABLE audit_logs ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE audit_logs ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_audit_logs_int_adr_action ON audit_logs (int_adr, action)');
        $this->addSql('CREATE INDEX idx_audit_logs_int_adr_created ON audit_logs (int_adr, created_at)');
        $this->addSql('CREATE INDEX idx_audit_logs_entity_actions ON audit_logs (entity_type, entity_id, action) WHERE ((entity_type IS NOT NULL) AND (entity_id IS NOT NULL))');
        $this->addSql('ALTER TABLE insyz_audit_logs DROP CONSTRAINT FK_1C3D7531A76ED395');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER id TYPE INT');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER id SET DEFAULT nextval(\'insyz_audit_logs_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER cache_hit TYPE BOOLEAN');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER cache_hit SET DEFAULT false');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER status TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER status SET DEFAULT \'success\'');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE insyz_audit_logs ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE insyz_audit_logs ADD CONSTRAINT fk_insyz_audit_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_insyz_audit_created_at ON insyz_audit_logs (created_at)');
        $this->addSql('CREATE INDEX idx_insyz_audit_duration ON insyz_audit_logs (duration_ms, created_at)');
        $this->addSql('CREATE INDEX idx_insyz_audit_mssql_duration ON insyz_audit_logs (mssql_duration_ms, created_at)');
        $this->addSql('ALTER TABLE system_options ALTER id TYPE INT');
        $this->addSql('ALTER TABLE system_options ALTER id SET DEFAULT nextval(\'system_options_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE system_options ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE system_options ALTER autoload TYPE BOOLEAN');
        $this->addSql('ALTER TABLE system_options ALTER autoload SET DEFAULT true');
        $this->addSql('ALTER TABLE system_options ALTER autoload DROP NOT NULL');
        $this->addSql('ALTER TABLE system_options ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE system_options ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE system_options ALTER created_at DROP NOT NULL');
        $this->addSql('ALTER TABLE system_options ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE system_options ALTER updated_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE system_options ALTER updated_at DROP NOT NULL');
        $this->addSql('ALTER INDEX uniq_3c468614b62dd4e5 RENAME TO system_options_option_name_key');
        $this->addSql('ALTER TABLE users ALTER id TYPE INT');
        $this->addSql('ALTER TABLE users ALTER id SET DEFAULT nextval(\'users_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE users ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE users ALTER roles TYPE JSON');
        $this->addSql('ALTER TABLE users ALTER roles SET DEFAULT \'["ROLE_USER"]\'');
        $this->addSql('ALTER TABLE users ALTER preferences TYPE JSON');
        $this->addSql('ALTER TABLE users ALTER preferences SET DEFAULT \'{}\'');
        $this->addSql('ALTER TABLE users ALTER settings TYPE JSON');
        $this->addSql('ALTER TABLE users ALTER settings SET DEFAULT \'{}\'');
        $this->addSql('ALTER TABLE users ALTER created_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE users ALTER created_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE users ALTER updated_at TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE users ALTER updated_at SET DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE users ALTER is_active TYPE BOOLEAN');
        $this->addSql('ALTER TABLE users ALTER is_active SET DEFAULT true');
        $this->addSql('CREATE INDEX idx_users_email ON users (email)');
        $this->addSql('CREATE INDEX idx_users_is_active ON users (is_active)');
        $this->addSql('CREATE INDEX idx_users_last_login ON users (last_login_at)');
        $this->addSql('ALTER INDEX uniq_1483a5e9d80ffe3d RENAME TO users_int_adr_key');
    }
}
