# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    App\Service\WorkerManagerService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\FileServeController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\HelpController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # API Exception listener pro JSON error responses
    App\EventListener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 100 }

    # Twig extension pro KČT komponenty
    App\Twig\KctExtension:
        tags:
            - { name: twig.extension }

    # Twig extension pro Tabler ikony
    App\Twig\TablerIconExtension:
        tags:
            - { name: twig.extension }

    # Twig extension pro uživatelské preference
    App\Twig\UserPreferenceExtension:
        tags:
            - { name: twig.extension }

    # Cache services konfigurace
    App\Service\ApiCacheService:
        arguments:
            $cache: '@cache.app'
            $logger: '@monolog.logger.api'

    App\Service\ApiMonitoringService:
        arguments:
            $logger: '@monolog.logger.api'

    # Image processing service konfigurace
    App\Service\ImageProcessingService: ~


    # MSSQL services konfigurace - clean without audit
    # App\Service\MssqlConnector: # uses default autowiring now

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
